name: "Release @neo4j-devtools/arc"

defaults:
  run:
    working-directory: src/neo4j-arc

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: neo4j/neo4j-browser
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@neo4j-devtools'
      - run: npm -g install yarn
      # - run: yarn test
      - run: yarn build
      - run: | 
          if [ $(npm view @neo4j-devtools/arc version) != $(npm view . version) ]; then
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
